In [55]:
import numpy as np #importing numpy
import time #importing time

# Creating Arrays

In [56]:
#creating a numpy array
arr1=np.array([1,2,3,4,5])

#creating a numpy array of random numbers
arr2=np.random.rand(5)

print("arr1: ",arr1)
print("arr2: ",arr2)

arr1:  [1 2 3 4 5]
arr2:  [0.01923495 0.32685337 0.34472442 0.85487526 0.60735457]


In [57]:
# 2d numpy array from 0-10 and 10-20
arr1=np.array([range(1,11),range(11,21)])
arr1.shape  # shape is the dimension, you generally go from outside to inside when validating the array shape

(2, 10)

In [58]:
# get certain element from the array
elem=arr1[0,8] # will get the element at 0th row and 8th column .i.e. 9
print("elem: ",elem)

elem:  9


In [59]:
# replace the element
arr1[0,8]=100 # the 9 will be replaced by 100
print("arr1: ",arr1)

arr1[0,5:8]=[100,200,300] # the 5th to 7th element will be replaced by 100,200,300
print("arr1: ",arr1)

# different dimensions
# arr1[0,5:8]=[100,200] # this will give an error because the dimensions are not the same

arr1:  [[  1   2   3   4   5   6   7   8 100  10]
 [ 11  12  13  14  15  16  17  18  19  20]]
arr1:  [[  1   2   3   4   5 100 200 300 100  10]
 [ 11  12  13  14  15  16  17  18  19  20]]


# Special Arrays

In [60]:
shape=(10000,10000)
# arrays with same nums can be created easily with some inbuilt funcs
s1=time.time()
zero=np.zeros(shape) # creates a 3x3 array with all zeros
e1=time.time()
zt=e1-s1

s2=time.time()
one=np.ones(shape) # creates a 3x3 array with all ones
e2=time.time()
ot=e2-s2

s3=time.time()
fs=np.full(shape,5) # creates a 3x3 array with all 5s
e3=time.time()
ft=e3-s3

s4=time.time()
em=np.empty(shape) # creates an empty 3x3 array
e4=time.time()
emt=e4-s4

# print("zero: ",zero)
# print("one: ",one)
# print("fs: ",fs)
# print("em: ",em)

In [61]:
print("zero time: ",zt) # ~200 times faster than ones and full
print("one time: ",ot)
print("fs time: ",ft)
print("em time: ",emt)# ~100 times faster than zeroes because initializes anything

zero time:  0.000995635986328125
one time:  0.1605696678161621
fs time:  0.07878923416137695
em time:  0.0


# Operations on a 3d array

In [62]:
#create a 3d array
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # think of this as a cube, the extra dimension is the depth
print(arr2)
arr1.shape

[0.01923495 0.32685337 0.34472442 0.85487526 0.60735457]


(2, 2, 3)

In [63]:
#getting certain elements from the array
elem1=arr1[0,:,2] # will get the element at 0th row, all columns and 2nd depth
print("elem1: ",elem1)

elem2=arr1[:,1,:] # will get the element at all rows, 1st column and all depths
print("elem2: ",elem2)

elem1:  [3 6]
elem2:  [[ 4  5  6]
 [10 11 12]]


In [64]:
#replacing certain elements
arr1[:,1,:]=[[21,22,23],[24,25,26]] # will replace the 1st column of all rows with 21,22,23 and 24,25,26
print(arr1)

[[[ 1  2  3]
  [21 22 23]]

 [[ 7  8  9]
  [24 25 26]]]


# Mathematical Operations and Linear Algebra

In [65]:
arr1=np.ones((2,3))
arr2=np.full((3,4),5)
ans1=arr1+1 # adds 1 to all elements of arr1
ans2=np.matmul(arr1,arr2) # multiplies arr1 and arr2

print("ans1: ",ans1)
print("ans2: ",ans2)

ans1:  [[2. 2. 2.]
 [2. 2. 2.]]
ans2:  [[15. 15. 15. 15.]
 [15. 15. 15. 15.]]


In [66]:
#trignometric functions
ans3=np.sin(arr1) # sin of arr1
print(ans3)

[[0.84147098 0.84147098 0.84147098]
 [0.84147098 0.84147098 0.84147098]]
